image: docker:stable

services:
  - docker:dind

stages:
  - build
  - start
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

start:
  stage: start
  script:
    - docker run $CI_REGISTRY_IMAGE npm start

deploy:
  stage: deploy
  script:
    - docker run -d --name my-node-app $CI_REGISTRY_IMAGE
