services:
  todo-database: 
    image: mongo

  todo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - todo-database
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
      - 35729:35729

  