services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3080:3080
    environment:
      MARIADB_ROOT_PASSWORD: baron

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:9080

  todo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - todo-database
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 35729:35729

  todo-database:
    image: mongo:6
    ports:
      - 27017:27017
